# Generated by Django 2.2 on 2019-06-13 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_records_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='records',
            name='status',
        ),
        migrations.AddField(
            model_name='records',
            name='config_weight',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='records',
            name='d_weight',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='records',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='records',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='records',
            name='total_time',
            field=models.IntegerField(default=0),
        ),
    ]
