# Generated by Django 2.2 on 2019-06-14 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_auto_20190613_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='actual_speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='records',
            name='speed',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
