# Generated by Django 2.2 on 2019-07-08 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0005_auto_20190614_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='screw_type',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
