# Generated by Django 2.2 on 2019-07-08 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0006_records_screw_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='total_time',
            field=models.FloatField(default=0),
        ),
    ]
